global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:3000

  - job_name: front
    metrics_path: /metrics
    static_configs:
      - targets:
          - front:8080

  - job_name: worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker:3002
